# TEST actions

name: check_actions

on: 
  push:
    branches:
    - master



jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
    - name: Printing Hello World
      run : echo "Hello world!"

    - name: Zip version
      run : zip --version

    - name: Docker status
      run : systemctl status docker

    - name: Check files
      run : ls -lah

    - name: Add git files
      uses: actions/checkout@v1

    - name: Check files again
      run : ls -lah
      
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
    - name: testing
      run : systemctl status docker
      
  test3:
    runs-on: ubuntu-latest
    needs: [test1, test2]
    steps:
    - name: testing
      run : systemctl status docker

  test4:
    runs-on: ubuntu-latest
    needs: test2
    steps:
    - name: testing
      run : systemctl status docker
